logLevel: info
logDestinations: [stdout]

authMethod: http
authHTTPAddress: http://api:8080/api/media/authorize
authHTTPExclude:
  - action: publish
  - action: api
  - action: metrics
  - action: pprof

rtsp: true
rtspAddress: :8554
rtspTransports: [tcp]

rtmp: false
webrtc: false
srt: false
moq: false

hls: true
hlsAddress: :8888
hlsEncryption: false
hlsAllowOrigins: ["http://localhost:3000", "http://localhost:5173"]
hlsAlwaysRemux: true
hlsVariant: mpegts
hlsSegmentCount: 6
hlsSegmentDuration: 2s

api: true
apiAddress: :9997

metrics: true
metricsAddress: :9998

playback: false

paths:
  camera-1:
    source: publisher
  camera-2:
    source: publisher
  camera-3:
    source: publisher
  camera-4:
    source: publisher
